# Generated by Django 4.2.6 on 2025-05-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='custom_url',
            field=models.CharField(blank=True, help_text='Явный URL', max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='named_url',
            field=models.CharField(blank=True, help_text='Имя URL-шаблона', max_length=100),
        ),
    ]
